//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductOfOrders = new HashSet<ProductOfOrder>();
        }
    
        public int idProduct { get; set; }
        public string nameProduct { get; set; }
        public double price { get; set; }
        public int unitsInStock { get; set; }
        public int numCategory { get; set; }
        public string color { get; set; }
        public string model { get; set; }
        public string size { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> showInSite { get; set; }
        public string img { get; set; }
        public int quentityInShop { get; set; }
        public string type { get; set; }
    
        public virtual OrderBasket OrderBasket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOfOrder> ProductOfOrders { get; set; }
    }
}
