//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditTable
    {
        public Nullable<int> idPlate { get; set; }
        public Nullable<int> idGlass { get; set; }
        public Nullable<int> idPlateBig { get; set; }
        public string imageAll { get; set; }
        public int id { get; set; }
    }
}
